"use client";

import { Activity, Check, LoaderCircle, Play, SlidersHorizontal, WandSparkles } from "lucide-react";
import { useEffect, useMemo, useState } from "react";

import { useStagePanels } from "@/components/workspace/WorkspacePanels";
import type { ObjectMaskingConfiguration } from "@/modules/360-player/types";
import type { Media } from "@/types/media";

interface VideoPreparationStageProps { projectId: string; video: Media; convertedViews: number; onComplete: (summary: { sampled: number; rejected: number }) => void; }
function mediaUrl(projectId: string, filepath: string) { return `/api/projects/${projectId}/media/${filepath.replace(/\\/g, "/").split("/").map(encodeURIComponent).join("/")}`; }

export default function VideoPreparationStage({ projectId, video, convertedViews, onComplete }: VideoPreparationStageProps) {
  const [fps, setFps] = useState(3); const [quality, setQuality] = useState(2); const [startTime, setStartTime] = useState(0); const [endTime, setEndTime] = useState<number | null>(null); const [processing, setProcessing] = useState(false); const [error, setError] = useState<string | null>(null); const [linkedViews, setLinkedViews] = useState(true); const [masking, setMasking] = useState<ObjectMaskingConfiguration | null>(null);
  const viewNames = ["front", "right", "back", "left", "up", "down"].slice(0, convertedViews);
  const setProfile = (profile: "raw" | "recommended" | "custom") => setMasking({ videoId: video.id, profile, removePeople: true, removeVehicles: true, removeOtherMovingObjects: true, sensitivity: profile === "raw" ? 0.45 : 0.7, temporalConsistency: profile === "raw" ? 0.55 : 0.8, startTime, endTime });
  const patchMask = (patch: Partial<ObjectMaskingConfiguration>) => masking && setMasking({ ...masking, ...patch });
  useEffect(() => { void (async () => { const response = await fetch(`/api/projects/${projectId}/process`); if (!response.ok) return; const result = await response.json() as { job?: { pipeline?: string; payload?: { settings?: { fps?: number; quality?: number; startTime?: number; endTime?: number | null; masking?: ObjectMaskingConfiguration | null } } } | null }; const settings = result.job?.pipeline === "frame-extraction" ? result.job.payload?.settings : null; if (!settings) return; if (settings.fps) setFps(settings.fps); if (settings.quality) setQuality(settings.quality); if (settings.startTime !== undefined) setStartTime(settings.startTime); if (settings.endTime !== undefined) setEndTime(settings.endTime); if (settings.masking) setMasking(settings.masking); })(); }, [projectId]);
  async function prepareFrames() { setProcessing(true); setError(null); try { const response = await fetch(`/api/projects/${projectId}/process`, { method: "POST", headers: { "Content-Type": "application/json" }, body: JSON.stringify({ pipeline: "frame-extraction", settings: { fps, quality, startTime, endTime, masking } }) }); const result = await response.json() as { error?: string; sampledFrames?: number; rejectedFrames?: number }; if (!response.ok) throw new Error(result.error ?? "Frame preparation failed."); if (response.status !== 202) onComplete({ sampled: result.sampledFrames ?? 0, rejected: result.rejectedFrames ?? 0 }); } catch (reason) { setError(reason instanceof Error ? reason.message : "Frame preparation failed."); } finally { setProcessing(false); } }
  const panels = useMemo(() => ({
    left: <div className="space-y-6"><section><p className="text-xs font-medium uppercase tracking-[.16em] text-zinc-500">Frame extraction</p><p className="mt-2 text-xs leading-5 text-zinc-500">Controls apply to {convertedViews ? `${convertedViews} projected views` : "the source clip"}. The recommended 3 fps preserves coverage for short captures.</p></section><section><label className="block text-xs text-zinc-300">Sampling <span className="float-right font-mono">{fps} fps</span><input className="mt-2 w-full accent-zinc-200" type="range" min="0.5" max="10" step="0.5" value={fps} onChange={(event) => setFps(Number(event.target.value))} /></label><div className="mt-2 grid grid-cols-3 gap-1">{[1, 3, 5].map((value) => <button key={value} onClick={() => setFps(value)} className={`border p-1.5 text-xs ${fps === value ? "border-zinc-200 bg-zinc-200 text-black" : "border-zinc-700 text-zinc-400"}`}>{value} fps</button>)}</div></section><section><label className="block text-xs text-zinc-300">JPEG quality <span className="float-right font-mono">{quality}</span><input className="mt-2 w-full accent-zinc-200" type="range" min="2" max="12" value={quality} onChange={(event) => setQuality(Number(event.target.value))} /></label></section><section className="grid grid-cols-2 gap-2"><label className="text-xs text-zinc-500">Start<input className="mt-1 w-full border border-zinc-700 bg-zinc-950 p-1.5 text-zinc-200" type="number" min="0" value={startTime} onChange={(event) => setStartTime(Number(event.target.value))} /></label><label className="text-xs text-zinc-500">End<input className="mt-1 w-full border border-zinc-700 bg-zinc-950 p-1.5 text-zinc-200" type="number" min="0" value={endTime ?? ""} onChange={(event) => setEndTime(event.target.value ? Number(event.target.value) : null)} /></label></section>{convertedViews > 1 ? <label className="flex justify-between border-y border-zinc-800 py-3 text-xs text-zinc-300">Link view settings<input checked={linkedViews} type="checkbox" onChange={(event) => setLinkedViews(event.target.checked)} /></label> : null}<button onClick={() => void prepareFrames()} disabled={processing} className="flex w-full items-center justify-center gap-2 bg-zinc-100 px-3 py-2.5 text-sm font-medium text-black disabled:opacity-50">{processing ? <LoaderCircle className="h-4 w-4 animate-spin" /> : <Play className="h-4 w-4" />}{processing ? "Preparing images…" : "Extract frames"}</button>{error ? <p className="border border-rose-900 bg-rose-950/30 p-2 text-xs text-rose-200">{error}</p> : null}</div>,
    right: <div className="space-y-6"><section><p className="text-xs font-medium uppercase tracking-[.16em] text-zinc-500">Dynamic objects</p><p className="mt-2 text-xs leading-5 text-zinc-500">The masking plan is saved with this job, but no segmentation engine is enabled yet. Frames are never falsely reported as masked.</p><div className="mt-3 grid gap-1">{(["raw", "recommended", "custom"] as const).map((profile) => <button key={profile} onClick={() => setProfile(profile)} className={`flex items-center justify-between border px-2 py-2 text-left text-xs capitalize ${masking?.profile === profile ? "border-amber-200 bg-amber-200 text-black" : "border-zinc-700 text-zinc-400"}`}>{profile === "raw" ? "Automatic" : profile}{masking?.profile === profile ? <Check className="h-3.5 w-3.5" /> : null}</button>)}</div>{masking?.profile === "custom" ? <div className="mt-3 space-y-3 border-t border-zinc-800 pt-3"><label className="block text-xs text-zinc-400">Sensitivity <span className="float-right">{Math.round(masking.sensitivity * 100)}%</span><input className="mt-2 w-full accent-amber-200" type="range" min="0.1" max="1" step="0.05" value={masking.sensitivity} onChange={(event) => patchMask({ sensitivity: Number(event.target.value) })} /></label><label className="block text-xs text-zinc-400">Temporal consistency<input className="mt-2 w-full accent-amber-200" type="range" min="0.1" max="1" step="0.05" value={masking.temporalConsistency} onChange={(event) => patchMask({ temporalConsistency: Number(event.target.value) })} /></label></div> : null}</section><section className="border-y border-zinc-800 py-4"><p className="flex items-center gap-2 text-xs font-medium text-zinc-300"><Activity className="h-3.5 w-3.5" /> Source telemetry</p><dl className="mt-3 space-y-2 text-xs text-zinc-500"><div className="flex justify-between"><dt>Source</dt><dd className="max-w-32 truncate">{video.filename}</dd></div><div className="flex justify-between"><dt>Projected views</dt><dd>{convertedViews || "Single"}</dd></div><div className="flex justify-between"><dt>Masking</dt><dd>{masking ? "Plan saved" : "Off"}</dd></div></dl></section><section><p className="text-xs font-medium uppercase tracking-[.16em] text-zinc-500">Output plan</p><p className="mt-2 text-sm leading-6 text-zinc-400">Raw candidates appear live in the gallery. OpenCV creates the separate accepted set used by reconstruction.</p></section></div>,
  }), [convertedViews, endTime, error, fps, linkedViews, masking, processing, quality, startTime, video.filename]);
  useStagePanels(panels);
  return <section className="flex h-full min-h-0 flex-col bg-[#0b0b0e] text-zinc-100"><header className="flex items-center justify-between border-b border-zinc-800 px-5 py-3"><div><p className="text-xs font-medium uppercase tracking-[.16em] text-zinc-500">Video workspace</p><h1 className="mt-1 text-lg font-medium">Frame preparation</h1></div><span className="text-xs text-zinc-500">{convertedViews ? `${convertedViews} camera views` : "Source video"}</span></header><main className="min-h-0 flex-1 p-5">{convertedViews ? <div className="grid h-full min-h-[20rem] grid-cols-2 gap-3 overflow-auto lg:grid-cols-3">{viewNames.map((view) => <article key={view} className="overflow-hidden border border-zinc-800 bg-black"><video className="aspect-video w-full object-cover" src={mediaUrl(projectId, `projects/${projectId}/processed/converted/${view}.mp4`)} controls muted playsInline preload="metadata" /><p className="px-3 py-2 text-xs capitalize text-zinc-400">{view} projection</p></article>)}</div> : <div className="grid h-full min-h-[20rem] place-items-center border border-zinc-800 bg-black"><video className="h-full max-h-full w-full object-contain" src={mediaUrl(projectId, video.filepath)} controls playsInline preload="metadata" /></div>}</main></section>;
}
